<!DOCTYPE html><html lang="fr"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Facture & Recu</title><link rel="stylesheet" href="{{ asset('legacy/assets/fontawesome/css/all.min.css') }}">@include('modules.professeur.bulletin.partials.styles')@include('modules.accounting.partials.styles')<style>.invoice{max-width:900px;margin:0 auto;background:white;color:#111827;border-radius:8px;padding:28px}.invoice-head{display:flex;justify-content:space-between;gap:20px;border-bottom:3px solid #00a843;padding-bottom:18px;margin-bottom:20px}.invoice-head img{max-width:90px}.invoice h2{color:#047857;text-transform:uppercase}.invoice table{width:100%;border-collapse:collapse}.invoice th,.invoice td{border:1px solid #cbd5e1;padding:10px}.invoice th{background:#ecfdf5}.invoice-foot{display:flex;justify-content:space-between;gap:24px;margin-top:38px}.sign{flex:1;text-align:center;border-top:1px solid #111827;padding-top:12px}.print-actions{text-align:center;margin:18px 0}.blank-line{color:#64748b;letter-spacing:2px}@media screen and (max-width:900px){body{overflow-x:hidden}.invoice{width:900px!important;max-width:900px!important;min-width:900px!important;margin-left:0!important;margin-right:0!important;zoom:.72;transform-origin:top left}.invoice-head{display:flex!important;flex-direction:row!important;align-items:flex-start!important}.invoice-head>div:last-child{text-align:right!important}.invoice table{display:table!important;width:100%!important;border-collapse:collapse!important}.invoice thead{display:table-header-group!important}.invoice tbody{display:table-row-group!important}.invoice tfoot{display:table-footer-group!important}.invoice tr{display:table-row!important;border:0!important;border-radius:0!important;margin:0!important;overflow:visible!important}.invoice th,.invoice td,.invoice tfoot th{display:table-cell!important;width:auto!important;position:static!important;padding:10px!important;min-height:0!important;text-align:inherit!important}.invoice td::before,.invoice tfoot th::before{display:none!important;content:none!important}.invoice-foot{display:flex!important;flex-direction:row!important;gap:24px!important}.sign{width:auto!important;flex:1!important}}@media screen and (max-width:760px){.invoice{zoom:.62}}@media screen and (max-width:700px){.invoice{zoom:.52}}@media screen and (max-width:600px){.invoice{zoom:.44}}@media screen and (max-width:520px){.invoice{zoom:.38}}@media screen and (max-width:380px){.invoice{zoom:.36}}@media print{.invoice{box-shadow:none;border-radius:0;max-width:none}.invoice th{background:#ecfdf5!important}}</style></head><body>
<style>@media print{@page{size:A4 portrait;margin:5mm}*,*::before,*::after{-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important}nav,header,footer,.burger-menu,#fullscreen-btn,.acc-panel,.no-print,.print-actions,.tabs,.novaskol-global-actions,.global-dropdown,.novaskol-loader{display:none!important}main{margin:0!important;padding:0!important;background:white!important;width:100%!important;display:flex!important;flex-direction:column!important;min-height:100vh!important}.invoice-copy{width:100%!important;float:none!important;margin:0!important;padding:3mm!important;box-sizing:border-box!important;background:white!important;color:#111!important;border:0!important;flex:1!important;display:flex!important;flex-direction:column!important;justify-content:center!important;min-height:0!important}.invoice-copy:first-of-type{border-bottom:2px dashed #999!important;margin-bottom:0!important}.invoice{width:100%!important;max-width:none!important;padding:0!important;background:white!important;color:#111!important}.invoice-head{padding-bottom:6px!important;margin-bottom:6px!important;page-break-inside:avoid!important;border-bottom-color:#047857!important}.invoice-head img{max-width:40px!important}.invoice-head h3{font-size:9pt!important;margin:0!important}.invoice-head h2{font-size:9pt!important;color:#047857!important;margin:0!important}.invoice-head p{font-size:7pt!important;margin:1px 0!important;color:#555!important}.invoice th{border-color:#cbd5e1!important;color:#111!important;padding:3px!important;font-size:7pt!important}.invoice td{border-color:#cbd5e1!important;color:#111!important;padding:3px!important;font-size:7pt!important}.invoice table{font-size:7pt!important}.invoice-foot{margin-top:6px!important}.sign{border-top-color:#111!important;color:#555!important;font-size:7pt!important;padding-top:4px!important}.blank-line{color:#999!important}.invoice p{font-size:7pt!important;margin:4px 0!important}}</style>
@include('modules.professeur.bulletin.partials.shell')<header><div class="header-left"><button class="burger-menu" onclick="toggleSidebar()"><i class="fa fa-bars"></i></button><button id="fullscreen-btn" onclick="toggleFullscreen()"><i class="fa fa-expand"></i></button></div><h1>Facture & Recu</h1></header>
<main>
<section class="acc-panel no-print"><form method="GET" class="acc-grid"><div><label>Document</label><select name="type_document"><option value="facture" @selected($docType==='facture')>Facture</option><option value="recu" @selected($docType==='recu')>Recu</option></select></div><div><label>Annee</label><select name="annee_scolaire" id="invoiceYear">@foreach($annees as $a)<option value="{{ $a }}" @selected($selectedAnnee===$a)>{{ $a }}</option>@endforeach</select></div><div><label>Mois</label><select name="mois"><option value="">Tous</option>@foreach($months as $m)<option value="{{ $m }}" @selected($selectedMonth===$m)>{{ $m }}</option>@endforeach</select></div><div style="position:relative"><label>Recherche personne</label><input type="text" id="invoiceSearch" placeholder="Eleve, enseignant ou staff"><div id="invoiceResults" class="acc-table-wrap" style="display:none;position:absolute;z-index:20;max-height:250px;overflow:auto;width:min(520px,90vw);"></div><input type="hidden" id="personne_id" name="personne_id" value="{{ $personneId }}"><input type="hidden" id="type_personne" name="type_personne" value="{{ $typePersonne }}"><div class="muted" id="pickedPerson">@if($personneId)Personne selectionnee #{{ $personneId }} ({{ $typePersonne }})@endif</div></div><button class="kaly">Generer</button><a class="kaly" href="{{ route('modules.facture',['type_document'=>'facture','blank'=>1]) }}">Facture vierge</a><a class="kaly" href="{{ route('modules.facture',['type_document'=>'recu','blank'=>1]) }}">Recu vierge</a></form></section>
@if($blank || $personneId)
<div class="print-actions"><button class="kaly" onclick="window.print()">Imprimer</button></div>
@php
$headOpen = '<div class="invoice-head"><div><img src="'.asset('legacy/images/'.(str_starts_with($ecole->logo ?? '', 'images/') ? substr($ecole->logo,7) : ($ecole->logo ?? 'novaskol.png'))).'" alt=""><h3>'.($ecole->nom ?? 'Ecole').'</h3></div><div style="text-align:right">';
$headClose = '<p>Date: '.date('d/m/Y').'</p><p>Annee: '.$selectedAnnee.'</p><p>Destinataire: '.($blank ? '<span class="blank-line">....................</span>' : (($transactions->first()->nom_personne ?? '-').' ('.$typePersonne.')')).'</p></div></div>';
$invoiceContentFacture = $headOpen.'<h2>FACTURE '.($blank ? '' : '#'.$numero).'</h2>'.$headClose;
$invoiceContentRecu = $headOpen.'<h2>RECU '.($blank ? '' : '#'.$numero).'</h2>'.$headClose;
$invoiceTable = '<table><thead><tr><th>Categorie</th><th>Description</th><th>Mode</th><th>Statut</th><th>Date</th><th>Montant</th></tr></thead><tbody>'; if($blank){ $invoiceTable .= '<tr><td data-label="Categorie">...</td><td data-label="Description">...</td><td data-label="Mode">...</td><td data-label="Statut">...</td><td data-label="Date">...</td><td data-label="Montant">...</td></tr>'; } else { foreach($transactions as $t){ $invoiceTable .= '<tr><td data-label="Categorie">'.$t->categorie.'</td><td data-label="Description">'.$t->description.'</td><td data-label="Mode">'.$t->mode_paiement.'</td><td data-label="Statut">'.$t->statut.'</td><td data-label="Date">'.$t->date_enregistrement.'</td><td data-label="Montant">'.number_format((float)$t->montant,0,',',' ').' '.novaskol_currency().'</td></tr>'; } } $invoiceTable .= '</tbody><tfoot><tr><th colspan="5" data-label="Total">Total</th><th data-label="Montant total">'.($blank ? '...' : number_format((float)$transactions->sum('montant'),0,',',' ').' '.novaskol_currency()).'</th></tr></tfoot></table>';
$footerFacture = '<p style="text-align:center;margin:28px 0">Veuillez effectuer le paiement dans les plus brefs delais.</p><div class="invoice-foot"><div class="sign">Signature</div><div class="sign">Cachet ecole</div></div>';
$footerRecu = '<p style="text-align:center;margin:28px 0">Merci pour votre reglement.</p><div class="invoice-foot"><div class="sign">Signature</div><div class="sign">Cachet ecole</div></div>';
@endphp
<div class="invoice-copy">
<section class="invoice">
{!! $invoiceContentFacture !!}
{!! $invoiceTable !!}
{!! $footerFacture !!}
</section>
</div>
<div class="invoice-copy">
<section class="invoice">
{!! $invoiceContentRecu !!}
{!! $invoiceTable !!}
{!! $footerRecu !!}
</section>
</div>
<div style="clear:both"></div>
@else
<section class="acc-panel"><p class="muted">Choisis une personne ou genere un document vierge.</p></section>
@endif
<footer>&copy; {{ date('Y') }} {{ $ecole->nom ?? 'Ecole' }}</footer></main><script>
function toggleSidebar(){document.getElementById('sidebar').classList.toggle('active')}function toggleSub(e){const n=e.nextElementSibling;if(n)n.style.display=n.style.display==='none'?'block':'none'}function toggleFullscreen(){document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen()}
let invTimer=null;document.getElementById('invoiceSearch')?.addEventListener('input',e=>{clearTimeout(invTimer);invTimer=setTimeout(async()=>{const q=e.target.value.trim();const box=document.getElementById('invoiceResults');if(q.length<2){box.style.display='none';return;}const annee=document.getElementById('invoiceYear').value;const r=await fetch(`{{ route('modules.facture.search-people') }}?annee_scolaire=${encodeURIComponent(annee)}&q=${encodeURIComponent(q)}`);const data=await r.json();box.innerHTML=data.map(p=>`<button type="button" style="display:block;width:100%;text-align:left;padding:10px;background:#111827;color:white;border:0;border-bottom:1px solid #1f2937" onclick="pickInvoicePerson(${p.id}, '${p.type_personne}', '${String(p.nom).replace(/'/g,'&#039;')}')">${p.nom} <span class="muted">${p.type_personne}</span></button>`).join('') || '<div class="muted" style="padding:10px">Aucun resultat</div>';box.style.display='block';},250)});
function pickInvoicePerson(id,type,nom){document.getElementById('personne_id').value=id;document.getElementById('type_personne').value=type;document.getElementById('pickedPerson').textContent=nom+' ('+type+')';document.getElementById('invoiceResults').style.display='none';document.getElementById('invoiceSearch').value=nom;}
</script></body></html>
