<!DOCTYPE html><html lang="fr"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Comptable</title><link rel="stylesheet" href="{{ asset('legacy/assets/fontawesome/css/all.min.css') }}">@include('modules.professeur.bulletin.partials.styles')@include('modules.accounting.partials.styles')</head><body>
@include('modules.professeur.bulletin.partials.shell')
<header><div class="header-left"><button class="burger-menu" onclick="toggleSidebar()"><i class="fa fa-bars"></i></button><button id="fullscreen-btn" onclick="toggleFullscreen()"><i class="fa fa-expand"></i></button></div><div class="header-center">Comptable</div></header>
<main>
<section class="acc-panel no-print"><form method="GET" class="acc-grid"><div><label>Annee scolaire</label><select name="annee_scolaire" onchange="this.form.submit()">@foreach($annees as $annee)<option value="{{ $annee }}" @selected($selectedAnnee===$annee)>{{ $annee }}</option>@endforeach</select></div></form></section>
<div class="tabs"><a class="tab-link active" href="#ecolage">Ecolage</a><a class="tab-link" href="#salaire">Salaire</a><a class="tab-link" href="#manuel">Operation manuelle</a></div>
<section id="ecolage" class="acc-panel"><h2>Paiement ecolage</h2><form method="POST" action="{{ route('modules.comptable.store') }}" class="acc-grid">@csrf<input type="hidden" name="kind" value="ecolage">
<div><label>Recherche eleve</label><input type="text" id="studentSearch" placeholder="Tape le nom ou prenom"><div id="studentResults" class="acc-table-wrap" style="display:none;position:absolute;z-index:20;max-height:240px;overflow:auto;width:min(520px,90vw);"></div></div>
<div><label>Eleve selectionne</label><select name="eleve_id" id="studentSelect" required>@foreach($students as $s)<option value="{{ $s->id }}" @selected($prefill['eleve_id']===(int)$s->id)>{{ $s->nom }} {{ $s->prenom }} - {{ $s->classe }}</option>@endforeach</select></div>
<div><label>Type paiement</label><select name="type_id" required>@foreach($paymentTypes as $t)<option value="{{ $t->id }}" @selected($prefill['type_id']===(int)$t->id) data-montant="{{ $t->montant }}">{{ $t->nom }} - {{ number_format((float)$t->montant,0,',',' ') }} {{ novaskol_currency() }}</option>@endforeach</select></div>
<div><label>Mois</label><select name="mois" required>@foreach($months as $m)<option value="{{ $m }}" @selected($prefill['mois']===$m)>{{ $m }}</option>@endforeach</select></div><div><label>Annee</label><input name="annee_scolaire" value="{{ $selectedAnnee }}"></div>
<div><label>Montant</label><input type="number" step="0.01" name="montant" required></div><div><label>Description</label><input name="description" value="Paiement ecolage"></div>
<div><label>Mode</label><select name="mode_paiement"><option>Especes</option><option>Cheque</option><option>Mobile Money</option><option>Virement</option></select></div><div><label>Statut</label><select name="statut"><option value="complet">Complet</option><option value="partiel">Partiel</option></select></div><div><label>Categorie</label><input name="categorie" value="Ecolage"></div><button class="kaly">Enregistrer</button></form></section>
<section id="salaire" class="acc-panel"><h2>Paiement salaire</h2><form method="POST" action="{{ route('modules.comptable.store') }}" class="acc-grid">@csrf<input type="hidden" name="kind" value="salaire">
<div><label>Type</label><select name="type_personne" id="type_personne"><option value="professeur" @selected($prefill['type_personne']==='professeur')>Professeur</option><option value="staff" @selected($prefill['type_personne']==='staff')>Staff</option></select></div>
<div><label>Personne</label><select name="personne_id" required><optgroup label="Professeurs">@foreach($teachers as $p)<option value="{{ $p->id }}" @selected($prefill['personne_id']===(int)$p->id && $prefill['type_personne']==='professeur')>{{ $p->nom }} {{ $p->prenom }}</option>@endforeach</optgroup><optgroup label="Staff">@foreach($staff as $p)<option value="{{ $p->id }}" @selected($prefill['personne_id']===(int)$p->id && $prefill['type_personne']==='staff')>{{ $p->nom }} {{ $p->prenom }}</option>@endforeach</optgroup></select></div>
<div><label>Mois</label><select name="mois" required>@foreach($months as $m)<option value="{{ $m }}" @selected($prefill['mois']===$m)>{{ $m }}</option>@endforeach</select></div><div><label>Annee</label><input name="annee_scolaire" value="{{ $selectedAnnee }}"></div>
<div><label>Montant</label><input type="number" step="0.01" name="montant" required></div><div><label>Description</label><input name="description" value="Paiement salaire"></div><div><label>Mode</label><select name="mode_paiement"><option>Especes</option><option>Cheque</option><option>Mobile Money</option><option>Virement</option></select></div><div><label>Statut</label><select name="statut"><option value="complet">Complet</option><option value="partiel">Partiel</option></select></div><div><label>Categorie</label><input name="categorie" value="Salaire"></div><button class="kaly">Enregistrer</button></form></section>
<section id="manuel" class="acc-panel"><h2>Operation manuelle</h2><form method="POST" action="{{ route('modules.comptable.store') }}" class="acc-grid">@csrf<input type="hidden" name="kind" value="manuel"><div><label>Flux</label><select name="flow"><option value="revenu">Revenu</option><option value="depense">Depense</option></select></div><div><label>Nom personne</label><input name="nom_personne" required></div><div><label>Type personne</label><input name="type_personne" value="autre"></div><div><label>Mois</label><select name="mois">@foreach($months as $m)<option value="{{ $m }}">{{ $m }}</option>@endforeach</select></div><div><label>Annee</label><input name="annee_scolaire" value="{{ $selectedAnnee }}"></div><div><label>Montant</label><input type="number" step="0.01" name="montant" required></div><div><label>Description</label><input name="description"></div><div><label>Mode</label><select name="mode_paiement"><option>Especes</option><option>Cheque</option><option>Mobile Money</option><option>Virement</option></select></div><div><label>Statut</label><select name="statut"><option value="complet">Complet</option><option value="partiel">Partiel</option></select></div><div><label>Categorie</label><input name="categorie" value="Operation"></div><button class="kaly">Enregistrer</button></form></section>
<footer>&copy; {{ date('Y') }} {{ $ecole->nom ?? 'Ecole' }}</footer></main><script>
function toggleSidebar(){document.getElementById('sidebar').classList.toggle('active')}function toggleSub(e){const n=e.nextElementSibling;if(n)n.style.display=n.style.display==='none'?'block':'none'}function toggleFullscreen(){document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen()}
const search=document.getElementById('studentSearch'), results=document.getElementById('studentResults'), select=document.getElementById('studentSelect');
let timer=null; search?.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(async()=>{const q=search.value.trim(); if(q.length<2){results.style.display='none';return;} const r=await fetch(`{{ route('modules.comptable.search-students') }}?annee_scolaire={{ urlencode($selectedAnnee) }}&q=${encodeURIComponent(q)}`); const data=await r.json(); results.innerHTML=data.map(s=>`<button type="button" style="display:block;width:100%;text-align:left;padding:10px;background:#111827;color:white;border:0;border-bottom:1px solid #1f2937" onclick="pickStudent(${s.id}, '${String(s.nom+' '+s.prenom+' - '+(s.classe||'')).replace(/'/g,'&#039;')}')">${s.nom} ${s.prenom} <span class="muted">${s.classe||''}</span></button>`).join('') || '<div class="muted" style="padding:10px">Aucun resultat</div>'; results.style.display='block';},250)});
function pickStudent(id,label){let opt=[...select.options].find(o=>Number(o.value)===id); if(!opt){opt=new Option(label,id); select.add(opt,0);} select.value=id; results.style.display='none'; search.value=label;}
document.querySelector('select[name="type_id"]')?.addEventListener('change',e=>{const m=e.target.selectedOptions[0]?.dataset.montant; const input=document.querySelector('#ecolage input[name="montant"]'); if(m&&input&&!input.value)input.value=m;});
</script>
<style>
@media print {
    @page { size:A4 portrait; margin:8mm; }
    *,*::before,*::after { -webkit-print-color-adjust:exact!important; print-color-adjust:exact!important; }
    html,body { background:white!important; color:#111!important; margin:0!important; padding:0!important; font-size:11pt!important; }
    nav,header,footer,.burger-menu,#fullscreen-btn,.tabs,.acc-panel,.no-print,.novaskol-global-actions,.global-dropdown,.novaskol-loader { display:none!important; }
    main { margin:0!important; padding:0!important; background:white!important; width:100%!important; }
    section.acc-panel { display:block!important; background:white!important; border:0!important; box-shadow:none!important; padding:0!important; margin:0 0 12mm!important; }
    section.acc-panel h2 { font-size:16pt!important; color:#065f46!important; text-align:center!important; margin-bottom:8px!important; }
    .acc-grid { display:block!important; }
    .acc-grid > div { margin-bottom:6px!important; }
    .acc-grid label { font-size:10pt!important; color:#333!important; display:inline!important; margin-right:8px!important; }
    .acc-grid input,.acc-grid select { font-size:10pt!important; display:inline!important; width:auto!important; min-width:140px!important; padding:4px 8px!important; border:1px solid #999!important; background:white!important; color:#111!important; }
    .kaly { display:none!important; }
}
</style>
</body></html>
