<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>FPE - Effectifs des Eleves - {{ $params['nom_ecole'] ?? ($ecole->nom ?? 'Ecole') }}</title>
<link rel="stylesheet" href="{{ asset('legacy/assets/fontawesome/css/all.min.css') }}">
<link rel="stylesheet" href="{{ asset('legacy/fa/css/font-awesome.min.css') }}">
<script src="{{ asset('legacy/js/jquery-3.6.0.min.js') }}"></script>
@include('modules.professeur.bulletin.partials.styles')
<style>
.form-container{width:100%;background:var(--card)!important;border-radius:12px;box-shadow:0 4px 15px var(--shadow-soft,rgba(0,0,0,.3));border:1px solid var(--border);padding:20px;overflow:hidden}.search-container{width:100%;max-width:100%;display:flex;gap:16px;margin:20px auto;flex-wrap:wrap}.search-container select,.search-container input,.search-container button{flex:1;min-width:200px;padding:12px;font-size:15px;border-radius:6px;border:1px solid var(--border);background:var(--surface);color:var(--text)}.search-container button{background:var(--primary);border:none;cursor:pointer;font-weight:500;color:#062b1d}.table-container{width:100%;max-width:100%;overflow-x:auto;-webkit-overflow-scrolling:touch;background:var(--card)!important;border:1px solid var(--border);border-radius:10px;margin:20px auto;box-shadow:0 4px 15px var(--shadow-soft,rgba(0,0,0,.3))}table{width:100%;border-collapse:separate;border-spacing:0;font-size:.8rem!important}th,td{padding:12px 16px;text-align:center;border:1px solid var(--border);color:var(--text)}th{background:var(--surface);color:var(--primary);font-weight:600;position:sticky;top:0;z-index:10;border:1px solid var(--border)}tr:hover td{background:var(--surface)}.total{font-weight:bold;background:rgba(148,163,184,.16)}.subtotal{font-weight:bold;background:rgba(5,150,105,.10)}.level-header{background:rgba(5,150,105,.16);font-weight:bold}.table-title{text-align:center;font-size:1rem;margin:30px 0 15px;color:var(--text-sec)}.header .school-info{text-align:left;margin-left:20px;color:var(--text)}.code{font-weight:bold;color:var(--primary);overflow-wrap:anywhere}.footer{text-align:center;margin-top:20px;color:var(--text-sec)}
@media screen and (max-width:900px){body{overflow-x:hidden}.form-container{padding:16px;overflow:hidden}.search-container{gap:10px}.search-container select,.search-container input,.search-container button{min-width:0;width:100%;flex:1 1 100%}.table-container{margin-top:14px;overflow:visible!important;border:0!important;box-shadow:none!important;background:transparent!important}.app>.header,.table-container>:not(.no-print),.app>.footer{width:1180px!important;max-width:1180px!important;min-width:1180px!important;margin-left:0!important;margin-right:0!important;zoom:.68;transform-origin:top left}.header .school-info{margin-left:20px!important;text-align:left!important}.table-title{font-size:1rem!important;line-height:1.35!important}table{width:100%!important;font-size:.8rem!important}th,td{padding:12px 16px!important}.footer{text-align:center!important}}
@media screen and (max-width:760px){.app>.header,.table-container>:not(.no-print),.app>.footer{zoom:.58}}
@media screen and (max-width:700px){.app>.header,.table-container>:not(.no-print),.app>.footer{zoom:.49}}
@media screen and (max-width:600px){.app>.header,.table-container>:not(.no-print),.app>.footer{zoom:.41}}
@media screen and (max-width:520px){.app>.header,.table-container>:not(.no-print),.app>.footer{zoom:.34}}
@media screen and (max-width:380px){.app>.header,.table-container>:not(.no-print),.app>.footer{zoom:.31}}
@media print{@page{size:A4 landscape;margin:10mm}*,*::before,*::after{-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important}body{background:#fff!important;color:#000!important;margin:0;padding:0;overflow:visible!important;font-size:10pt!important}.header{margin-bottom:0;padding-top:0!important}.header .school-info{margin-left:24px!important;color:#000!important;font-size:11pt!important}.header .code{font-size:10pt!important}main{background:#fff!important;margin:0!important;padding:12mm 10mm!important;overflow:visible!important}.table-container,.footer{page-break-inside:auto;background:#fff!important;color:#000!important;border:0!important;box-shadow:none!important;overflow:visible!important;zoom:1!important;transform:none!important}.app>.header,.table-container>:not(.no-print),.app>.footer{width:auto!important;max-width:none!important;min-width:0!important;zoom:1!important;transform:none!important}table{page-break-inside:auto;width:100%!important;table-layout:auto;color:black!important}.table-title{text-align:center;font-size:11pt!important;margin:20px 0 12px;color:#111!important}table tr{page-break-inside:avoid;page-break-after:auto;color:black!important}table th,table td{border:1px solid #000;background:#fff!important;font-size:7.5pt!important;padding:3px 4px!important;color:black!important}table th{background:#e5e7eb!important;color:#111!important;font-weight:700}.total{background-color:#d1d5db!important}.subtotal{background-color:#e5e7eb!important}.level-header{background-color:#9ca3af!important;color:white!important}.no-print,.burger-menu,nav,header,.form-container>.app>.footer,main>footer,.novaskol-global-actions,.global-dropdown,.novaskol-loader,.kaly{display:none!important;zoom:1!important;transform:none!important}.search-container select,.search-container input,.search-container button{display:none!important}.app{display:block!important}.form-container{display:block!important;background:#fff!important;border:0!important;box-shadow:none!important;padding:0!important;margin:0!important;zoom:1!important;transform:none!important}}
</style>
</head>
<body>
@include('modules.professeur.bulletin.partials.shell', ['activeModule' => $activeModule])
<main>
<header><div class="header-left"><button class="burger-menu" onclick="toggleSidebar()"><i class="fa fa-bars"></i></button><button id="fullscreen-btn" onclick="toggleFullscreen()"><i id="fullscreen-icon" class="fa fa-expand"></i></button></div><h1><i class="fa fa-table"></i> FPE - Effectifs des Eleves</h1></header>
<div class="form-container"><div class="app">
<div class="header"><div class="school-info"><div>{{ $params['nom_ecole'] ?? ($ecole->nom ?? 'Ecole') }}</div><div class="code">RECOPIER LE CODE DE L'ETABLISSEMENT: {{ $params['code_etablissement'] ?? 'N/A' }}</div></div></div>
<div class="table-container">
<div class="no-print"><form class="search-container" method="GET" action="{{ route('modules.fpe') }}"><select name="classe"><option value="0">-- Toutes les classes --</option>@foreach($fpe['classes'] as $c)<option value="{{ $c->id }}" @selected($selectedClasse===$c->id)>{{ $c->nom }}</option>@endforeach</select><select name="annee">@foreach($annees as $annee)<option value="{{ $annee }}" @selected($selectedAnnee===$annee)>{{ $annee }}</option>@endforeach</select><select name="version"><option value="simple" @selected($version==='simple')>Version Simple (Secondaire et Tertiaire)</option><option value="complete" @selected($version==='complete')>Version Complete (Toutes les classes)</option></select><button type="submit">Afficher</button><button type="button" onclick="window.print()">Imprimer</button><button class="kaly" style="background:#333!important;padding:10px 16px;font-size:13px;display:inline-block;text-decoration:none;color:#fff;border-radius:6px;margin-left:8px" onclick="window.print()">Apercu PDF</button></form></div>

@if($version === 'complete')
<div class="table-title">INFORMATIONS SUR LES ELEVES</div>
<div class="table-title">E1. TABLEAU DES EFFECTIFS GLOBAUX DU PRESCOLAIRE ET PRIMAIRE PAR CLASSE ET PAR GENRE (Y COMPRIS LES ELEVES EN SITUATION DE HANDICAP (ESH)) (mettre zero s'il n'y en a pas)</div>
<table><thead><tr><th></th><th colspan="{{ max(1,$fpe['preschoolClasses']->count()*2) }}">PRESCOLAIRE</th><th colspan="{{ max(1,$fpe['primaryClasses']->count()*2) }}">PRIMAIRE</th><th colspan="2">TOTAL</th></tr><tr><th></th>@foreach($fpe['preschoolClasses'] as $classe)<th colspan="2">{{ $classe->nom }}</th>@endforeach @foreach($fpe['primaryClasses'] as $classe)<th colspan="2">{{ $classe->nom }}</th>@endforeach<th>G</th><th>F</th></tr><tr><th></th>@foreach($fpe['preschoolClasses'] as $classe)<th>G</th><th>F</th>@endforeach @foreach($fpe['primaryClasses'] as $classe)<th>G</th><th>F</th>@endforeach<th>G</th><th>F</th></tr></thead><tbody>
@foreach(array_slice($fpe['categoriesPrimary'],0,6,true) as $key=>$label)<tr><td>{{ $label }}</td>@foreach($fpe['preschoolClasses'] as $classe)<td>{{ $fpe['dataPrimary'][$key][$classe->nom]['G'] ?? 0 }}</td><td>{{ $fpe['dataPrimary'][$key][$classe->nom]['F'] ?? 0 }}</td>@endforeach @foreach($fpe['primaryClasses'] as $classe)<td>{{ $fpe['dataPrimary'][$key][$classe->nom]['G'] ?? 0 }}</td><td>{{ $fpe['dataPrimary'][$key][$classe->nom]['F'] ?? 0 }}</td>@endforeach<td>{{ $fpe['totalsPrimary'][$key]['G'] ?? 0 }}</td><td>{{ $fpe['totalsPrimary'][$key]['F'] ?? 0 }}</td></tr>@endforeach
</tbody></table>

<div class="table-title">E2. INFORMATIONS SUR LES ELEVES</div>
<table><thead><tr><th></th><th colspan="{{ max(1,$fpe['preschoolClasses']->count()*2) }}">PRESCOLAIRE</th><th colspan="{{ max(1,$fpe['primaryClasses']->count()*2) }}">PRIMAIRE</th><th colspan="2">TOTAL</th></tr><tr><th></th>@foreach($fpe['preschoolClasses'] as $classe)<th colspan="2">{{ $classe->nom }}</th>@endforeach @foreach($fpe['primaryClasses'] as $classe)<th colspan="2">{{ $classe->nom }}</th>@endforeach<th>G</th><th>F</th></tr><tr><th></th>@foreach($fpe['preschoolClasses'] as $classe)<th>G</th><th>F</th>@endforeach @foreach($fpe['primaryClasses'] as $classe)<th>G</th><th>F</th>@endforeach<th>G</th><th>F</th></tr></thead><tbody>
@foreach(array_slice($fpe['categoriesPrimary'],6,1,true) as $key=>$label)<tr><td>{{ $label }}</td>@foreach($fpe['preschoolClasses'] as $classe)<td>{{ $fpe['dataPrimary'][$key][$classe->nom]['G'] ?? 0 }}</td><td>{{ $fpe['dataPrimary'][$key][$classe->nom]['F'] ?? 0 }}</td>@endforeach @foreach($fpe['primaryClasses'] as $classe)<td>{{ $fpe['dataPrimary'][$key][$classe->nom]['G'] ?? 0 }}</td><td>{{ $fpe['dataPrimary'][$key][$classe->nom]['F'] ?? 0 }}</td>@endforeach<td>{{ $fpe['totalsPrimary'][$key]['G'] ?? 0 }}</td><td>{{ $fpe['totalsPrimary'][$key]['F'] ?? 0 }}</td></tr>@endforeach
</tbody></table>

<div class="table-title">REPARTITION PAR AGE DES EFFECTIFS DES ELEVES DU PRESCOLAIRE ET PRIMAIRE PAR CLASSE ET PAR GENRE</div>
<table><thead><tr><th></th><th colspan="{{ max(1,$fpe['preschoolClasses']->count()*2) }}">PRESCOLAIRE</th><th colspan="{{ max(1,$fpe['primaryClasses']->count()*2) }}">PRIMAIRE</th><th colspan="2">TOTAL</th></tr><tr><th></th>@foreach($fpe['preschoolClasses'] as $classe)<th colspan="2">{{ $classe->nom }}</th>@endforeach @foreach($fpe['primaryClasses'] as $classe)<th colspan="2">{{ $classe->nom }}</th>@endforeach<th>G</th><th>F</th></tr><tr><th></th>@foreach($fpe['preschoolClasses'] as $classe)<th>G</th><th>F</th>@endforeach @foreach($fpe['primaryClasses'] as $classe)<th>G</th><th>F</th>@endforeach<th>G</th><th>F</th></tr></thead><tbody>
@foreach($fpe['primaryAges'] as $age)<tr><td>{{ $age }}</td>@foreach($fpe['preschoolClasses'] as $classe)<td @if(in_array($age,$fpe['primarySpecific'],true)) style="background-color:#a0a0a0" @endif>{{ $fpe['dataPrimaryAge'][$classe->nom][$age]['G'] ?? 0 }}</td><td @if(in_array($age,$fpe['primarySpecific'],true)) style="background-color:#a0a0a0" @endif>{{ $fpe['dataPrimaryAge'][$classe->nom][$age]['F'] ?? 0 }}</td>@endforeach @foreach($fpe['primaryClasses'] as $classe)<td @if(in_array($age,$fpe['preschoolSpecific'],true)) style="background-color:#a0a0a0" @endif>{{ $fpe['dataPrimaryAge'][$classe->nom][$age]['G'] ?? 0 }}</td><td @if(in_array($age,$fpe['preschoolSpecific'],true)) style="background-color:#a0a0a0" @endif>{{ $fpe['dataPrimaryAge'][$classe->nom][$age]['F'] ?? 0 }}</td>@endforeach<td>{{ $fpe['totalsPrimaryAge'][$age]['G'] ?? 0 }}</td><td>{{ $fpe['totalsPrimaryAge'][$age]['F'] ?? 0 }}</td></tr>@endforeach
<tr class="total"><td>TOTAL</td>@foreach($fpe['preschoolClasses'] as $classe)<td>{{ array_sum(array_column($fpe['dataPrimaryAge'][$classe->nom] ?? [], 'G')) }}</td><td>{{ array_sum(array_column($fpe['dataPrimaryAge'][$classe->nom] ?? [], 'F')) }}</td>@endforeach @foreach($fpe['primaryClasses'] as $classe)<td>{{ array_sum(array_column($fpe['dataPrimaryAge'][$classe->nom] ?? [], 'G')) }}</td><td>{{ array_sum(array_column($fpe['dataPrimaryAge'][$classe->nom] ?? [], 'F')) }}</td>@endforeach<td>{{ array_sum(array_column($fpe['totalsPrimaryAge'], 'G')) }}</td><td>{{ array_sum(array_column($fpe['totalsPrimaryAge'], 'F')) }}</td></tr>
</tbody></table>

<div class="table-title">E3. REPARTITION PAR AGE DES REDOUBLANTS EN CLASSE DE CP ET CM2 PAR GENRE</div>
<table><thead><tr><th>REDOUBLANTS</th><th>SEXE</th>@foreach($fpe['redoublantsAges'] as $age)<th>{{ $age }}</th>@endforeach<th>TOTAL</th></tr></thead><tbody>
@foreach(['CP','CM2'] as $className)@foreach(['G','F'] as $genre)<tr>@if($genre==='G')<td rowspan="2">{{ $className }}</td>@endif<td>{{ $genre }}</td>@foreach($fpe['redoublantsAges'] as $age)<td>{{ $fpe['dataRedoublants'][$className][$age][$genre] ?? 0 }}</td>@endforeach<td>{{ $fpe['totalsRedoublants'][$className][$genre] ?? 0 }}</td></tr>@endforeach @endforeach
</tbody></table><div style="page-break-before:always"></div>
@endif

<div class="table-title">F.4. TABLEAU DES EFFECTIFS GLOBAUX PAR NIVEAU ET PAR GENRE</div>
<table><thead><tr><th></th><th colspan="{{ max(1,$fpe['collegeClasses']->count()*2) }}" class="level-header">College</th><th colspan="{{ max(1,$fpe['lyceeClasses']->count()*2) }}" class="level-header">Lycee</th><th colspan="2">T</th></tr><tr><th></th>@foreach($fpe['collegeClasses'] as $classe)<th colspan="2">{{ $classe->nom }}</th>@endforeach @foreach($fpe['lyceeClasses'] as $classe)<th colspan="2">{{ $classe->nom }}</th>@endforeach<th>G</th><th>F</th></tr><tr><th></th>@foreach($fpe['collegeClasses'] as $classe)<th>G</th><th>F</th>@endforeach @foreach($fpe['lyceeClasses'] as $classe)<th>G</th><th>F</th>@endforeach<th>G</th><th>F</th></tr></thead><tbody>
@foreach($fpe['categoriesF4'] as $key=>$label)<tr><td style="padding:0!important">{{ $label }}</td>@foreach($fpe['collegeClasses'] as $classe)<td>{{ $fpe['dataF4'][$key][$classe->nom]['G'] ?? 0 }}</td><td>{{ $fpe['dataF4'][$key][$classe->nom]['F'] ?? 0 }}</td>@endforeach @foreach($fpe['lyceeClasses'] as $classe)<td>{{ $fpe['dataF4'][$key][$classe->nom]['G'] ?? 0 }}</td><td>{{ $fpe['dataF4'][$key][$classe->nom]['F'] ?? 0 }}</td>@endforeach<td>{{ $fpe['totalsF4'][$key]['G'] ?? 0 }}</td><td>{{ $fpe['totalsF4'][$key]['F'] ?? 0 }}</td></tr>@endforeach
<tr class="subtotal"><td>Sous-total College</td>@foreach($fpe['collegeClasses'] as $classe)<td colspan="2"></td>@endforeach @foreach($fpe['lyceeClasses'] as $classe)<td colspan="2"></td>@endforeach<td>{{ $fpe['subtotalsCollegeF4']['effectif']['G'] ?? 0 }}</td><td>{{ $fpe['subtotalsCollegeF4']['effectif']['F'] ?? 0 }}</td></tr>
<tr class="subtotal"><td>Sous-total Lycee</td>@foreach($fpe['collegeClasses'] as $classe)<td colspan="2"></td>@endforeach @foreach($fpe['lyceeClasses'] as $classe)<td colspan="2"></td>@endforeach<td>{{ $fpe['subtotalsLyceeF4']['effectif']['G'] ?? 0 }}</td><td>{{ $fpe['subtotalsLyceeF4']['effectif']['F'] ?? 0 }}</td></tr>
</tbody></table>

<div class="table-title">F.5. REPARTITION PAR AGE DES EFFECTIFS DES ELEVES PAR NIVEAU ET PAR GENRE</div>
<table><thead><tr><th></th><th colspan="{{ max(1,$fpe['collegeClasses']->count()*2) }}" class="level-header">College</th><th colspan="{{ max(1,$fpe['lyceeClasses']->count()*2) }}" class="level-header">Lycee</th><th colspan="2">T</th></tr><tr><th></th>@foreach($fpe['collegeClasses'] as $classe)<th colspan="2">{{ $classe->nom }}</th>@endforeach @foreach($fpe['lyceeClasses'] as $classe)<th colspan="2">{{ $classe->nom }}</th>@endforeach<th>G</th><th>F</th></tr><tr><th></th>@foreach($fpe['collegeClasses'] as $classe)<th>G</th><th>F</th>@endforeach @foreach($fpe['lyceeClasses'] as $classe)<th>G</th><th>F</th>@endforeach<th>G</th><th>F</th></tr></thead><tbody>
@foreach($fpe['agesSecondary'] as $age)<tr><td>{{ is_numeric($age) ? $age.' ans' : $age }}</td>@foreach($fpe['collegeClasses'] as $classe)<td>{{ $fpe['dataF5'][$classe->nom][$age]['G'] ?? 0 }}</td><td>{{ $fpe['dataF5'][$classe->nom][$age]['F'] ?? 0 }}</td>@endforeach @foreach($fpe['lyceeClasses'] as $classe)<td>{{ $fpe['dataF5'][$classe->nom][$age]['G'] ?? 0 }}</td><td>{{ $fpe['dataF5'][$classe->nom][$age]['F'] ?? 0 }}</td>@endforeach<td>{{ $fpe['totalsF5'][$age]['G'] ?? 0 }}</td><td>{{ $fpe['totalsF5'][$age]['F'] ?? 0 }}</td></tr>@endforeach
<tr class="total"><td>TOTAL</td>@foreach($fpe['collegeClasses'] as $classe)<td>{{ array_sum(array_column($fpe['dataF5'][$classe->nom] ?? [], 'G')) }}</td><td>{{ array_sum(array_column($fpe['dataF5'][$classe->nom] ?? [], 'F')) }}</td>@endforeach @foreach($fpe['lyceeClasses'] as $classe)<td>{{ array_sum(array_column($fpe['dataF5'][$classe->nom] ?? [], 'G')) }}</td><td>{{ array_sum(array_column($fpe['dataF5'][$classe->nom] ?? [], 'F')) }}</td>@endforeach<td>{{ array_sum(array_column($fpe['totalsF5'], 'G')) }}</td><td>{{ array_sum(array_column($fpe['totalsF5'], 'F')) }}</td></tr>
<tr class="subtotal"><td>Sous-total College</td>@foreach($fpe['collegeClasses'] as $classe)<td colspan="2"></td>@endforeach @foreach($fpe['lyceeClasses'] as $classe)<td colspan="2"></td>@endforeach<td>{{ array_sum(array_column($fpe['subtotalsCollegeF5'], 'G')) }}</td><td>{{ array_sum(array_column($fpe['subtotalsCollegeF5'], 'F')) }}</td></tr>
<tr class="subtotal"><td>Sous-total Lycee</td>@foreach($fpe['collegeClasses'] as $classe)<td colspan="2"></td>@endforeach @foreach($fpe['lyceeClasses'] as $classe)<td colspan="2"></td>@endforeach<td>{{ array_sum(array_column($fpe['subtotalsLyceeF5'], 'G')) }}</td><td>{{ array_sum(array_column($fpe['subtotalsLyceeF5'], 'F')) }}</td></tr>
</tbody></table>
</div><div class="footer"><p>Imprime le {{ date('d/m/Y a H:i') }} EAT - {{ $params['nom_ecole'] ?? ($ecole->nom ?? 'Ecole') }}</p></div>
</div></div><footer>&copy; {{ date('Y') }} {{ $ecole->nom ?? 'Ecole' }}. Tous droits reserves.</footer></main>
<script>
function toggleSidebar(){document.querySelector('nav').classList.toggle('active');document.querySelector('main').classList.toggle('full-width');document.querySelector('header').classList.toggle('full-width')}function toggleSub(e){const s=e.nextElementSibling,a=e.querySelector('.arrow');s.style.display=s.style.display==='block'?'none':'block';a.classList.toggle('fa-chevron-down');a.classList.toggle('fa-chevron-up')}function toggleFullscreen(){const i=document.getElementById('fullscreen-icon');if(!document.fullscreenElement){document.documentElement.requestFullscreen();i.classList.replace('fa-expand','fa-compress')}else{document.exitFullscreen();i.classList.replace('fa-compress','fa-expand')}}document.addEventListener('DOMContentLoaded',()=>{const a=document.querySelector('nav a.active'),s=a?.closest('.sub-menu');if(s){s.style.display='block';s.previousElementSibling?.querySelector('.arrow')?.classList.replace('fa-chevron-down','fa-chevron-up')}})
</script>
</body></html>
