<style>
    .settings-panel{background:var(--card);border:1px solid var(--border);border-radius:8px;padding:22px;margin-bottom:18px}
    .settings-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:16px}
    .settings-section{margin-bottom:26px}.settings-section h2{color:var(--primary);font-size:1.18rem;margin:0 0 14px;border-bottom:1px solid rgba(0,200,83,.28);padding-bottom:8px}
    label{display:block;color:var(--text-sec);font-weight:700;margin:0 0 6px}input,textarea,select{width:100%;padding:12px;background:var(--surface);color:var(--text);border:1px solid var(--border);border-radius:8px}textarea{resize:vertical}.field{min-width:0}.check-field{display:flex;gap:10px;align-items:center;background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:12px}.check-field input{width:auto}.logo-preview{width:120px;height:120px;object-fit:contain;background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:8px;margin-top:10px}.alert{padding:12px 14px;border-radius:8px;margin-bottom:16px}.alert.success{background:rgba(0,200,83,.13);border:1px solid rgba(0,200,83,.35);color:#86efac}.alert.error{background:rgba(239,68,68,.12);border:1px solid rgba(239,68,68,.35);color:#fecaca}
    .backup-actions{display:flex;gap:12px;flex-wrap:wrap;align-items:center;justify-content:center}.backup-summary{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:14px;margin:18px 0}.backup-kpi{background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:16px}.backup-kpi span{display:block;color:var(--text-sec);font-size:.85rem}.backup-kpi strong{display:block;color:var(--primary);font-size:1.3rem;margin-top:6px}.settings-table-wrap{overflow:auto;-webkit-overflow-scrolling:touch;max-width:100%;border:1px solid var(--border);border-radius:8px;background:var(--card)}.settings-table{width:100%;border-collapse:collapse;min-width:720px}.settings-table th,.settings-table td{padding:12px;border-bottom:1px solid var(--border);text-align:left;color:var(--text);vertical-align:top}.settings-table th{background:var(--surface);color:var(--primary);text-transform:uppercase;font-size:.78rem}.settings-actions{display:flex;gap:8px;flex-wrap:wrap}.btn-small{border:0;border-radius:8px;padding:9px 12px;color:white;text-decoration:none;cursor:pointer;font-weight:700}.download{background:#00a843}.delete{background:#ef4444}.muted{color:var(--text-sec)}
    @media(max-width:900px){.settings-panel{padding:16px}.settings-actions{flex-direction:column}.btn-small{width:100%;text-align:center}}
    @media(max-width:760px){.settings-section h2{font-size:1.02rem}.settings-table{min-width:0}.settings-table-wrap{overflow:visible;border:0;background:transparent}.settings-table thead{display:none}.settings-table,.settings-table tbody,.settings-table tr,.settings-table td{display:block;width:100%}.settings-table tr{margin-bottom:14px;border:1px solid var(--border);border-radius:10px;background:var(--card);overflow:hidden}.settings-table td{border-bottom:1px solid var(--border);padding:12px 14px 12px 46%;position:relative;min-height:48px}.settings-table td:last-child{border-bottom:0}.settings-table td::before{content:attr(data-label);position:absolute;left:14px;top:12px;width:calc(46% - 22px);color:var(--text-sec);font-weight:800;font-size:.76rem;text-transform:uppercase;line-height:1.3}.settings-actions{margin-top:4px}}
</style>
